version: "3.3"
services:
  api:
    build:
      context: .
      dockerfile: dockerfile.api
    image: wormpicker-api
    container_name: wormpicker-api
    sysctls:
      - net.ipv4.tcp_keepalive_time=200
    ports:
      - ${API_PORT:-5000}:5000
    restart: always
  client:
    build:
      context: .
      dockerfile: dockerfile.client
    image: wormpicker-client
    container_name: wormpicker-client
    depends_on:
      - api
    ports:
      - ${CLIENT_PORT:-80}:80
    restart: always
